### ISSUE TITLE
Fine tuning the alert 

### ISSUE THREAD

**Issue by puteen0001** [JouniMi/Threathunt.blog#1]
Kindly help with conditions to fine tune the alert in order to reduce the processes. Whitelisting the processes is not ideal. Thank you

**Comment by puteen0001** [comment]
@JouniMi

**Comment by JouniMi** [comment]
Unfortunately these queries are provided as is, I am not able to provide individual assistance in tuning them to be suitable in any particular instance. Hope you understand!
